// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcPsthy7ebcekMXe_EnN4BAyxZiscKsY',
    appId: '1:280072689577:web:e72a5f228d19d8f86716b8',
    messagingSenderId: '280072689577',
    projectId: 'gram-8f465',
    authDomain: 'gram-8f465.firebaseapp.com',
    storageBucket: 'gram-8f465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IS_0LnFURLIum03ZwuY68Yw_hI17Tu0',
    appId: '1:280072689577:android:a998572fbd6dd9746716b8',
    messagingSenderId: '280072689577',
    projectId: 'gram-8f465',
    storageBucket: 'gram-8f465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ5wyC32KHFG8ipUeQlIgpaG784pXgxaU',
    appId: '1:280072689577:ios:1871465e5480999d6716b8',
    messagingSenderId: '280072689577',
    projectId: 'gram-8f465',
    storageBucket: 'gram-8f465.appspot.com',
    iosClientId: '280072689577-6bcmqrs5k5lbaqpvfnhnhlfk83va3mgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ5wyC32KHFG8ipUeQlIgpaG784pXgxaU',
    appId: '1:280072689577:ios:1871465e5480999d6716b8',
    messagingSenderId: '280072689577',
    projectId: 'gram-8f465',
    storageBucket: 'gram-8f465.appspot.com',
    iosClientId: '280072689577-6bcmqrs5k5lbaqpvfnhnhlfk83va3mgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gram',
  );
}
